搬运Davkas mod语言模板，修正链接标签，修正隔热导线的翻译错位及标签错误
ONI-Wiki-zh/ONIi18n pull request #21
Opened 2022-01-22 07:21 UTC by CialloAlone

两年前我为Davkas的模组提供了中文翻译，但目前在游戏中似乎有部分未能正确显示，这次对原模组的模板文件进行修正，顺便将翻译搬运到这边

2022-01-22 19:24 UTC, DDEle commented
ru 的翻译也是您做的么？如果不是，感觉在取得原译者同意前还是先删了比较好

2022-01-22 19:25 UTC, DDEle requested changes

2022-01-22 19:25 UTC, DDEle commented on strings/Insulated_Door/ru.po
> +msgid ""
ru 的翻译也是您做的么？如果不是，感觉在取得原译者同意前还是先删了比较好

2022-01-23 11:53 UTC, CialloAlone commented on strings/Insulated_Door/ru.po
> +msgid ""
确实未经授权搬运其他译者的翻译是我欠考虑了，我先将其他翻译移除了，稍后提交到原作者那边，然后在steam尝试向译者征求一下搬运意见

2022-01-23 17:23 UTC, DDEle approved these changes

2022-01-23 17:23 UTC, merged